# Generated by Django 3.2.9 on 2022-09-16 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Manufacturer', models.CharField(max_length=70)),
                ('Image', models.ImageField(default='default.jpg', upload_to='media')),
                ('CPU', models.CharField(max_length=100)),
                ('GPU', models.CharField(blank=True, max_length=100)),
                ('OS', models.CharField(max_length=100)),
                ('Ports', models.CharField(max_length=100)),
                ('Screen_resolution', models.CharField(max_length=100)),
                ('Screen_size', models.CharField(max_length=100)),
                ('Screen_panel_type', models.CharField(blank=True, max_length=100)),
                ('Web_camera', models.CharField(blank=True, max_length=100)),
                ('Main_camera', models.CharField(blank=True, max_length=100)),
                ('Front_camera', models.CharField(blank=True, max_length=100)),
                ('Screen_refresh_rate', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Category', models.ForeignKey(default='uncategorised', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.category')),
            ],
        ),
    ]
